const cidades = [
    { id: 1, Municipio: "Abreu e Lima", Texto: "Texto Abreu e Lima.", concorrentes: [] },
{ id: 2, Municipio: "Afrânio", Texto: "Texto Afrânio.", concorrentes: [] },
{ id: 3, Municipio: "Agrestina", Texto: "Texto Agrestina.", concorrentes: [] },
{ id: 4, Municipio: "Alagoinha", Texto: "Texto Alagoinha.", concorrentes: [] },
{ id: 5, Municipio: "Altinho", Texto: "Texto Altinho.", concorrentes: [] },
{ id: 6, Municipio: "Amaraji", Texto: "Texto Amaraji.", concorrentes: [] },
{ id: 7, Municipio: "Angelim", Texto: "Texto Angelim.", concorrentes: [] },
{ id: 8, Municipio: "Araçoiaba", Texto: "Texto Araçoiaba.", concorrentes: [] },
{ id: 9, Municipio: "Barreiros", Texto: "Texto Barreiros.", concorrentes: [] },
{ id: 10, Municipio: "Barro", Texto: "Texto Barro.", concorrentes: [] },
{ id: 11, Municipio: "Beijupirá", Texto: "Texto Beijupirá.", concorrentes: [] },
{ id: 12, Municipio: "Belém de Maria", Texto: "Texto Belém de Maria.", concorrentes: [] },
{ id: 13, Municipio: "Belém do São Francisco", Texto: "Texto Belém do São Francisco.", concorrentes: [] },
{ id: 14, Municipio: "Belo Jardim", Texto: "Texto Belo Jardim.", concorrentes: [] },
{ id: 15, Municipio: "Betânia", Texto: "Texto Betânia.", concorrentes: [] },
{ id: 16, Municipio: "Bezerros", Texto: "Texto Bezerros.", concorrentes: [] },
{ id: 17, Municipio: "Bonito", Texto: "Texto Bonito.", concorrentes: [] },
{ id: 18, Municipio: "Brejo da Madre de Deus", Texto: "Texto Brejo da Madre de Deus.", concorrentes: [] },
{ id: 19, Municipio: "Brejão", Texto: "Texto Brejão.", concorrentes: [] },
{ id: 20, Municipio: "Buenos Aires", Texto: "Texto Buenos Aires.", concorrentes: [] },
{ id: 21, Municipio: "Buíque", Texto: "Texto Buíque.", concorrentes: [] },
{ id: 22, Municipio: "Cachoeirinha", Texto: "Texto Cachoeirinha.", concorrentes: [] },
{ id: 23, Municipio: "Caetés", Texto: "Texto Caetés.", concorrentes: [] },
{ id: 24, Municipio: "Calumbi", Texto: "Texto Calumbi.", concorrentes: [] },
{ id: 25, Municipio: "Camaragibe", Texto: "Texto Camaragibe.", concorrentes: [] },
{ id: 26, Municipio: "Camocim de São Félix", Texto: "Texto Camocim de São Félix.", concorrentes: [] },
{ id: 27, Municipio: "Carnaíba", Texto: "Texto Carnaíba.", concorrentes: [] },
{ id: 28, Municipio: "Caruaru", Texto: "Texto Caruaru.", concorrentes: [] },
{ id: 29, Municipio: "Casserengue", Texto: "Texto Casserengue.", concorrentes: [] },
{ id: 30, Municipio: "Catende", Texto: "Texto Catende.", concorrentes: [] },
{ id: 31, Municipio: "Cedro", Texto: "Texto Cedro.", concorrentes: [] },
{ id: 32, Municipio: "Chã Grande", Texto: "Texto Chã Grande.", concorrentes: [] },
{ id: 33, Municipio: "Chã Preta", Texto: "Texto Chã Preta.", concorrentes: [] },
{ id: 34, Municipio: "Chã do Pilar", Texto: "Texto Chã do Pilar.", concorrentes: [] },
{ id: 35, Municipio: "Condado", Texto: "Texto Condado.", concorrentes: [] },
{ id: 36, Municipio: "Correntes", Texto: "Texto Correntes.", concorrentes: [] },
{ id: 37, Municipio: "Cortês", Texto: "Texto Cortês.", concorrentes: [] },
{ id: 38, Municipio: "Custódia", Texto: "Texto Custódia.", concorrentes: [] },
{ id: 39, Municipio: "Dormentes", Texto: "Texto Dormentes.", concorrentes: [] },
{ id: 40, Municipio: "Escada", Texto: "Texto Escada.", concorrentes: [] },
{ id: 41, Municipio: "Exu", Texto: "Texto Exu.", concorrentes: [] },
{ id: 42, Municipio: "Feira Nova", Texto: "Texto Feira Nova.", concorrentes: [] },
{ id: 43, Municipio: "Fernando de Noronha", Texto: "Texto Fernando de Noronha.", concorrentes: [] },
{ id: 44, Municipio: "Ferreiros", Texto: "Texto Ferreiros.", concorrentes: [] },
{ id: 45, Municipio: "Floresta", Texto: "Texto Floresta.", concorrentes: [] },
{ id: 46, Municipio: "Frei Miguelinho", Texto: "Texto Frei Miguelinho.", concorrentes: [] },
{ id: 47, Municipio: "Gameleira", Texto: "Texto Gameleira.", concorrentes: [] },
{ id: 48, Municipio: "Garanhuns", Texto: "Texto Garanhuns.", concorrentes: [] },
{ id: 49, Municipio: "Glória do Goitá", Texto: "Texto Glória do Goitá.", concorrentes: [] },
{ id: 50, Municipio: "Goiana", Texto: "Texto Goiana.", concorrentes: [] },
{ id: 51, Municipio: "Gravatá", Texto: "Texto Gravatá.", concorrentes: [] },
{ id: 52, Municipio: "Iati", Texto: "Texto Iati.", concorrentes: [] },
{ id: 53, Municipio: "Ibiporã", Texto: "Texto Ibiporã.", concorrentes: [] },
{ id: 54, Municipio: "Igarassu", Texto: "Texto Igarassu.", concorrentes: [] },
{ id: 55, Municipio: "Igaracy", Texto: "Texto Igaracy.", concorrentes: [] },
{ id: 56, Municipio: "Inajá", Texto: "Texto Inajá.", concorrentes: [] },
{ id: 57, Municipio: "Ingazeira", Texto: "Texto Ingazeira.", concorrentes: [] },
{ id: 58, Municipio: "Ipojuca", Texto: "Texto Ipojuca.", concorrentes: [] },
{ id: 59, Municipio: "Jaboatão dos Guararapes", Texto: "Texto Jaboatão dos Guararapes.", concorrentes: [] },
{ id: 60, Municipio: "Jaqueira", Texto: "Texto Jaqueira.", concorrentes: [] },
{ id: 61, Municipio: "Jataúba", Texto: "Texto Jataúba.", concorrentes: [] },
{ id: 62, Municipio: "João Alfredo", Texto: "Texto João Alfredo.", concorrentes: [] },
{ id: 63, Municipio: "João Pessoa", Texto: "Texto João Pessoa.", concorrentes: [] },
{ id: 64, Municipio: "Joaquim Nabuco", Texto: "Texto Joaquim Nabuco.", concorrentes: [] },
{ id: 65, Municipio: "Jucati", Texto: "Texto Jucati.", concorrentes: [] },
{ id: 66, Municipio: "Jupi", Texto: "Texto Jupi.", concorrentes: [] },
{ id: 67, Municipio: "Jurema", Texto: "Texto Jurema.", concorrentes: [] },
{ id: 68, Municipio: "Lagoa do Carro", Texto: "Texto Lagoa do Carro.", concorrentes: [] },
{ id: 69, Municipio: "Lagoa Grande", Texto: "Texto Lagoa Grande.", concorrentes: [] },
{ id: 70, Municipio: "Limoeiro", Texto: "Texto Limoeiro.", concorrentes: ["Ongold Tech"] },
{ id: 71, Municipio: "Macaparana", Texto: "Texto Macaparana.", concorrentes: [] },
{ id: 72, Municipio: "Machados", Texto: "Texto Machados.", concorrentes: [] },
{ id: 73, Municipio: "Moreno", Texto: "Texto Moreno.", concorrentes: [] },
{ id: 74, Municipio: "Nazaré da Mata", Texto: "Texto Nazaré da Mata.", concorrentes: [] },
{ id: 75, Municipio: "Orobó", Texto: "Texto Orobó.", concorrentes: [] },
{ id: 76, Municipio: "Ouricuri", Texto: "Texto Ouricuri.", concorrentes: [] },
{ id: 77, Municipio: "Palmares", Texto: "Texto Palmares.", concorrentes: [] },
{ id: 78, Municipio: "Panelas", Texto: "Texto Panelas.", concorrentes: [] },
{ id: 79, Municipio: "Passira", Texto: "Texto Passira.", concorrentes: [] },
{ id: 80, Municipio: "Paudalho", Texto: "Texto Paudalho.", concorrentes: [] },
{ id: 81, Municipio: "Paulista", Texto: "Texto Paulista.", concorrentes: [] },
{ id: 82, Municipio: "Petrolândia", Texto: "Texto Petrolândia.", concorrentes: [] },
{ id: 83, Municipio: "Petrolina", Texto: "Texto Petrolina.", concorrentes: [] },
{ id: 84, Municipio: "Pesqueira", Texto: "Texto Pesqueira.", concorrentes: [] },
{ id: 85, Municipio: "Piedade", Texto: "Texto Piedade.", concorrentes: [] },
{ id: 86, Municipio: "Pindoba", Texto: "Texto Pindoba.", concorrentes: [] },
{ id: 87, Municipio: "Pombos", Texto: "Texto Pombos.", concorrentes: [] },
{ id: 88, Municipio: "Poção", Texto: "Texto Poção.", concorrentes: [] },
{ id: 89, Municipio: "Primavera", Texto: "Texto Primavera.", concorrentes: [] },
{ id: 90, Municipio: "Quipapá", Texto: "Texto Quipapá.", concorrentes: [] },
{ id: 91, Municipio: "Quixaba", Texto: "Texto Quixaba.", concorrentes: [] },
{ id: 92, Municipio: "Recife", Texto: "Texto Recife.", concorrentes: [] },
{ id: 93, Municipio: "Riacho das Almas", Texto: "Texto Riacho das Almas.", concorrentes: [] },
{ id: 94, Municipio: "Ribeirão", Texto: "Texto Ribeirão.", concorrentes: [] },
{ id: 95, Municipio: "Rio Formoso", Texto: "Texto Rio Formoso.", concorrentes: [] },
{ id: 96, Municipio: "Sairé", Texto: "Texto Sairé.", concorrentes: [] },
{ id: 97, Municipio: "Salgadinho", Texto: "Texto Salgadinho.", concorrentes: [] },
{ id: 98, Municipio: "Salgueiro", Texto: "Texto Salgueiro.", concorrentes: [] },
{ id: 99, Municipio: "Sanharó", Texto: "Texto Sanharó.", concorrentes: [] },
{ id: 100, Municipio: "Santa Cruz do Capibaribe", Texto: "Texto Santa Cruz do Capibaribe.", concorrentes: [] },
{ id: 101, Municipio: "Santa Filomena", Texto: "Texto Santa Filomena.", concorrentes: [] },
{ id: 102, Municipio: "Santa Maria do Cambucá", Texto: "Texto Santa Maria do Cambucá.", concorrentes: [] },
{ id: 103, Municipio: "Santa Terezinha", Texto: "Texto Santa Terezinha.", concorrentes: [] },
{ id: 104, Municipio: "São Bento do Una", Texto: "Texto São Bento do Una.", concorrentes: [] },
{ id: 105, Municipio: "São Caitano", Texto: "Texto São Caitano.", concorrentes: [] },
{ id: 106, Municipio: "São João", Texto: "Texto São João.", concorrentes: [] },
{ id: 107, Municipio: "São Joaquim do Monte", Texto: "Texto São Joaquim do Monte.", concorrentes: [] },
{ id: 108, Municipio: "São José da Coroa Grande", Texto: "Texto São José da Coroa Grande.", concorrentes: [] },
{ id: 109, Municipio: "São José do Belmonte", Texto: "Texto São José do Belmonte.", concorrentes: [] },
{ id: 110, Municipio: "São Lourenço da Mata", Texto: "Texto São Lourenço da Mata.", concorrentes: [] },
{ id: 111, Municipio: "São Vicente Ferrer", Texto: "Texto São Vicente Ferrer.", concorrentes: [] },
{ id: 112, Municipio: "Serra Talhada", Texto: "Texto Serra Talhada.", concorrentes: [] },
{ id: 113, Municipio: "Sertânia", Texto: "Texto Sertânia.", concorrentes: [] },
{ id: 114, Municipio: "Sirinhaém", Texto: "Texto Sirinhaém.", concorrentes: [] },
{ id: 115, Municipio: "Solidão", Texto: "Texto Solidão.", concorrentes: [] },
{ id: 116, Municipio: "Surubim", Texto: "Texto Surubim.", concorrentes: [] },
{ id: 117, Municipio: "Tamandaré", Texto: "Texto Tamandaré.", concorrentes: [] },
{ id: 118, Municipio: "Taquaritinga do Norte", Texto: "Texto Taquaritinga do Norte.", concorrentes: [] },
{ id: 119, Municipio: "Terezinha", Texto: "Texto Terezinha.", concorrentes: [] },
{ id: 120, Municipio: "Timbaúba", Texto: "Texto Timbaúba.", concorrentes: [] },
{ id: 121, Municipio: "Toritama", Texto: "Texto Toritama.", concorrentes: [] },
{ id: 122, Municipio: "Tracunhaém", Texto: "Texto Tracunhaém.", concorrentes: [] },
{ id: 123, Municipio: "Trindade", Texto: "Texto Trindade.", concorrentes: [] },
{ id: 124, Municipio: "Vertentes", Texto: "Texto Vertentes.", concorrentes: [] },
{ id: 125, Municipio: "Vitória de Santo Antão", Texto: "Texto Vitória de Santo Antão.", concorrentes: [] },
{ id: 126, Municipio: "Arcoverde", Texto: "Texto Arcoverde.", concorrentes: [] },
{ id: 127, Municipio: "Barra de Guabiraba", Texto: "Texto Barra de Guabiraba.", concorrentes: [] },
{ id: 128, Municipio: "Belo Jardim", Texto: "Texto Belo Jardim.", concorrentes: [] },
{ id: 129, Municipio: "São José do Egito", Texto: "Texto São José do Egito.", concorrentes: [] },
{ id: 130, Municipio: "Quipapá", Texto: "Texto Quipapá.", concorrentes: [] },
{ id: 131, Municipio: "Cupira", Texto: "Texto Cupira.", concorrentes: [] },
{ id: 132, Municipio: "Jataúba", Texto: "Texto Jataúba.", concorrentes: [] },
{ id: 133, Municipio: "Brejinho", Texto: "Texto Brejinho.", concorrentes: [] },
{ id: 134, Municipio: "Riacho das Almas", Texto: "Texto Riacho das Almas.", concorrentes: [] },
{ id: 135, Municipio: "São José do Belmonte", Texto: "Texto São José do Belmonte.", concorrentes: [] },
{ id: 136, Municipio: "Surubim", Texto: "Texto Surubim.", concorrentes: [] },
{ id: 137, Municipio: "Triunfo", Texto: "Texto Triunfo.", concorrentes: [] },
{ id: 138, Municipio: "Ipubi", Texto: "Texto Ipubi.", concorrentes: [] },
{ id: 139, Municipio: "Inajá", Texto: "Texto Inajá.", concorrentes: [] },
{ id: 140, Municipio: "Aliança", Texto: "Texto Aliança.", concorrentes: [] },
{ id: 141, Municipio: "Serrita", Texto: "Texto Serrita.", concorrentes: [] },
{ id: 142, Municipio: "Santa Cruz", Texto: "Texto Santa Cruz.", concorrentes: [] },
{ id: 143, Municipio: "Bom Jardim", Texto: "Texto Bom Jardim.", concorrentes: [] },
{ id: 144, Municipio: "São Lourenço", Texto: "Texto São Lourenço.", concorrentes: [] },
{ id: 145, Municipio: "Jaboatão", Texto: "Texto Jaboatão.", concorrentes: [] },
{ id: 146, Municipio: "Moreno", Texto: "Texto Moreno.", concorrentes: [] },
{ id: 147, Municipio: "São Vicente", Texto: "Texto São Vicente.", concorrentes: [] },
{ id: 148, Municipio: "Casinhas", Texto: "Texto Casinhas.", concorrentes: [] },
{ id: 149, Municipio: "São Joaquim", Texto: "Texto São Joaquim.", concorrentes: [] },
{ id: 150, Municipio: "João Alfredo", Texto: "Texto João Alfredo.", concorrentes: [] },
{ id: 151, Municipio: "Glória", Texto: "Texto Glória.", concorrentes: [] },
{ id: 152, Municipio: "São Pedro", Texto: "Texto São Pedro.", concorrentes: [] },
{ id: 153, Municipio: "São Benedito", Texto: "Texto São Benedito.", concorrentes: [] },
{ id: 154, Municipio: "São Miguel", Texto: "Texto São Miguel.", concorrentes: [] },
{ id: 155, Municipio: "Lagoa do Ouro", Texto: "Texto Lagoa do Ouro.", concorrentes: [] },
{ id: 156, Municipio: "Betânia", Texto: "Texto Betânia.", concorrentes: [] },
{ id: 157, Municipio: "Correntes", Texto: "Texto Correntes.", concorrentes: [] },
{ id: 158, Municipio: "Pesqueira", Texto: "Texto Pesqueira.", concorrentes: [] },
{ id: 159, Municipio: "Igaracy", Texto: "Texto Igaracy.", concorrentes: [] },
{ id: 160, Municipio: "Granito", Texto: "Texto Granito.", concorrentes: [] },
{ id: 161, Municipio: "São Bento", Texto: "Texto São Bento.", concorrentes: [] },
{ id: 162, Municipio: "Sertânia", Texto: "Texto Sertânia.", concorrentes: [] },
{ id: 163, Municipio: "Buique", Texto: "Texto Buique.", concorrentes: [] },
{ id: 164, Municipio: "Itacuruba", Texto: "Texto Itacuruba.", concorrentes: [] },
{ id: 165, Municipio: "Tuparetama", Texto: "Texto Tuparetama.", concorrentes: [] },
{ id: 166, Municipio: "Afogados da Ingazeira", Texto: "Texto Afogados da Ingazeira.", concorrentes: [] },
{ id: 167, Municipio: "Flores", Texto: "Texto Flores.", concorrentes: [] },
{ id: 168, Municipio: "São José", Texto: "Texto São José.", concorrentes: [] },
{ id: 169, Municipio: "Macaparana", Texto: "Texto Macaparana.", concorrentes: [] },
{ id: 170, Municipio: "São Domingos", Texto: "Texto São Domingos.", concorrentes: [] },
{ id: 171, Municipio: "São Sebastião", Texto: "Texto São Sebastião.", concorrentes: [] },
{ id: 172, Municipio: "Moreilândia", Texto: "Texto Moreilândia.", concorrentes: [] },
{ id: 173, Municipio: "Carnaíba", Texto: "Texto Carnaíba.", concorrentes: [] },
{ id: 174, Municipio: "Jaboatão", Texto: "Texto Jaboatão.", concorrentes: [] },
{ id: 175, Municipio: "São Caetano", Texto: "Texto São Caetano.", concorrentes: [] },
{ id: 176, Municipio: "Araçoiaba", Texto: "Texto Araçoiaba.", concorrentes: [] },
{ id: 177, Municipio: "Surubim", Texto: "Texto Surubim.", concorrentes: [] },
{ id: 178, Municipio: "Petrolândia", Texto: "Texto Petrolândia.", concorrentes: [] },
{ id: 179, Municipio: "Jatobá", Texto: "Texto Jatobá.", concorrentes: [] },
{ id: 180, Municipio: "Quipapá", Texto: "Texto Quipapá.", concorrentes: [] },
{ id: 181, Municipio: "Lagoa", Texto: "Texto Lagoa.", concorrentes: [] },
{ id: 182, Municipio: "Pedra", Texto: "Texto Pedra.", concorrentes: [] },
{ id: 183, Municipio: "Santa Maria", Texto: "Texto Santa Maria.", concorrentes: [] },
{ id: 184, Municipio: "Serra Talhada", Texto: "Texto Serra Talhada.", concorrentes: [] },
];

export default cidades;